
import java.util.Random;
import java.util.Scanner;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Family
 */
public class number extends javax.swing.JFrame {
    Random D = new Random();  
    Scanner pro;
    
    int vec = 0;
    int vector[] = new int[1000];
    int choke[] = new int[1000];
    int Pares[] = new int [1000];
    int vic=0;
    int ganador=0;
    int i = 0;
    /**
     * Creates new form NumberRace
     */
    public number() {
        initComponents();
        
        btnTry.setEnabled(false); 
        btnAbout.setEnabled(false);  
        btnConfigParams.setEnabled(false);  
        btnplay.setEnabled(false);
        pnlZonePlay.setEnabled(false);
        lblD1.setEnabled(false);
        lblD2.setEnabled(false);
        
        
        
//        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlZonePlay = new javax.swing.JPanel();
        lblD2 = new javax.swing.JLabel();
        lblD1 = new javax.swing.JLabel();
        btnplay = new javax.swing.JButton();
        pnlConfigZone = new javax.swing.JPanel();
        cbxLeven = new javax.swing.JComboBox<>();
        btnStart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxNumP = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        pnlPairs = new javax.swing.JPanel();
        lblPares = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnConfigParams = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnTry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number race");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Number race");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 20, 250, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car64px.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 80, 70);

        pnlZonePlay.setBackground(new java.awt.Color(204, 204, 204));
        pnlZonePlay.setBorder(javax.swing.BorderFactory.createTitledBorder("Play zone"));
        pnlZonePlay.setLayout(null);

        lblD2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblD2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pregunta.png"))); // NOI18N
        pnlZonePlay.add(lblD2);
        lblD2.setBounds(200, 70, 64, 70);

        lblD1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblD1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pregunta.png"))); // NOI18N
        pnlZonePlay.add(lblD1);
        lblD1.setBounds(60, 70, 70, 70);

        btnplay.setText("play  -  player ");
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        pnlZonePlay.add(btnplay);
        btnplay.setBounds(60, 180, 190, 40);

        jPanel1.add(pnlZonePlay);
        pnlZonePlay.setBounds(320, 250, 310, 240);

        pnlConfigZone.setBorder(javax.swing.BorderFactory.createTitledBorder("config zone"));

        cbxLeven.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-> Basic = 50", "-> Intermdiate = 100", "-> Advanced = 200" }));
        cbxLeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLevenActionPerformed(evt);
            }
        });

        btnStart.setText("Start gamer");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel3.setText("Number of players");

        jLabel4.setText("Level");

        cbxNumP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-> 1", "-> 2", "-> 3" }));
        cbxNumP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNumPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConfigZoneLayout = new javax.swing.GroupLayout(pnlConfigZone);
        pnlConfigZone.setLayout(pnlConfigZoneLayout);
        pnlConfigZoneLayout.setHorizontalGroup(
            pnlConfigZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigZoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConfigZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxLeven, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cbxNumP, 0, 184, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConfigZoneLayout.setVerticalGroup(
            pnlConfigZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigZoneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(cbxNumP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxLeven, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlConfigZone);
        pnlConfigZone.setBounds(30, 80, 210, 220);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Scores zone"));

        jLabel5.setText("turn player:");

        jLabel6.setText("advance positions:");

        jLabel7.setText("Missing positions ");

        jLabel8.setText("Returns");

        lbl4.setText("-");

        lbl3.setText("-");

        lbl2.setText("-");

        lbl1.setText("-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl4))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(670, 80, 230, 220);

        pnlPairs.setBorder(javax.swing.BorderFactory.createTitledBorder("pairs"));
        pnlPairs.setToolTipText("");

        lblPares.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblPares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPares.setText("0");

        javax.swing.GroupLayout pnlPairsLayout = new javax.swing.GroupLayout(pnlPairs);
        pnlPairs.setLayout(pnlPairsLayout);
        pnlPairsLayout.setHorizontalGroup(
            pnlPairsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPairsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPares, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        pnlPairsLayout.setVerticalGroup(
            pnlPairsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPairsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPares, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jPanel1.add(pnlPairs);
        pnlPairs.setBounds(40, 340, 160, 140);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Winner"));
        jPanel6.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("?");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(710, 320, 170, 150);

        btnConfigParams.setText("Config params");
        jPanel1.add(btnConfigParams);
        btnConfigParams.setBounds(360, 160, 210, 30);

        btnAbout.setText("About of");
        jPanel1.add(btnAbout);
        btnAbout.setBounds(360, 120, 210, 30);

        btnTry.setText("Try Again");
        btnTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryActionPerformed(evt);
            }
        });
        jPanel1.add(btnTry);
        btnTry.setBounds(360, 80, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
         //TODO add your handling code here:
        
         
        pnlZonePlay.setEnabled(true);
        lblD1.setEnabled(true);
        lblD2.setEnabled(true);
        btnplay.setEnabled(true);
        btnTry.setEnabled(true);    
        btnAbout.setEnabled(true);  
        btnConfigParams.setEnabled(true); 
        btnplay.setText("Play - Player 1");
        
        
            
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void cbxNumPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNumPActionPerformed
        // TODO add your handling code here:
        
        String NumJugadores = null;
        NumJugadores = NumJugadores+cbxNumP.getSelectedItem().toString();
        
        
        
    }//GEN-LAST:event_cbxNumPActionPerformed

    private void cbxLevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLevenActionPerformed
        // TODO add your handling code here:
        String leven = null;
        leven = leven+cbxLeven.getSelectedItem().toString();
    }//GEN-LAST:event_cbxLevenActionPerformed

    private void btnTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryActionPerformed
         lblD1.setIcon(new ImageIcon(getClass().getResource("images/pregunta.png")));
         lblD2.setIcon(new ImageIcon(getClass().getResource("images/pregunta.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTryActionPerformed

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
        // TODO add your handling code here:
//        int n=0;
//        n = Integer.parseInt(cbxNumP.getSelectedItem().toString());
//        String lev = cbxLeven.getSelectedItem().toString();
//        
//        int op = 0;
//        switch (op){
//            case 1:
//            "Basic".equals(lev);
//            break;
//            case 2:
//            "Intermediate".equals(lev);
//            break;
//            case 3:
//            "Advance".equals(lev);
//            break;
//        }
        
        
        
        Random D = new Random();
           int d1 = 0, d2 = 0;

        d1 = (int)(D.nextDouble()* 6 + 1);
        d2 = (int)(D.nextDouble()* 6 + 1);
        int res;
        res = d1+d2;

//        lbl1.setText(Integer.toString(d1));
        if (res==2){
            res = 21;
        }
        lbl2.setText(Integer.toString(res));
        
        
        switch (d1){
            case 1:
            lblD1.setIcon(new ImageIcon(getClass().getResource("images/1.png")));
            break;
            case 2:
            lblD1.setIcon(new ImageIcon(getClass().getResource("images/2.png")));
            break;
            case 3:
            lblD1.setIcon(new ImageIcon(getClass().getResource("images/3.png")));
            break;
            case 4:
            lblD1.setIcon(new ImageIcon(getClass().getResource("images/4.png")));
            break;
            case 5:
            lblD1.setIcon(new ImageIcon(getClass().getResource("images/5.png")));
            break;
            case 6:
            lblD1.setIcon(new ImageIcon(getClass().getResource("images/6.png")));
            break;
            default:

            break;

        }

        switch (d2){

            case 1:
            lblD2.setIcon(new ImageIcon(getClass().getResource("images/1.png")));
            break;
            case 2:
            lblD2.setIcon(new ImageIcon(getClass().getResource("images/2.png")));
            break;
            case 3:
            lblD2.setIcon(new ImageIcon(getClass().getResource("images/3.png")));
            break;
            case 4:
            lblD2.setIcon(new ImageIcon(getClass().getResource("images/4.png")));
            break;
            case 5:
            lblD2.setIcon(new ImageIcon(getClass().getResource("images/5.png")));
            break;
            case 6:
            lblD2.setIcon(new ImageIcon(getClass().getResource("images/6.png")));
            break;
            default:

            break;
            
        }
            
            
                
            
        
        
        
        
//        
//        
//        int elec=0;
//        switch (elec){
//            case 1:
//                if (vic<50){
//                    
//                    System.out.println("la meta  es = 50");
//                    System.out.println("la posicion del jugador("+i+")="+ vector[i]); 
//                    
//                        if(vector[i]+6<50){
//                            System.out.println("jigador"+i);
//                            lbl1.setText(String.valueOf(i));
//                            System.out.println("presione enter para lanzar los dados");
//                            
////                            Random D = new Random();
////                            int d1 = 0, d2 = 0;
////
////                            d1 = (int)(D.nextDouble()* 6 + 1);
////                            d2 = (int)(D.nextDouble()* 6 + 1);
////                            System.out.println("dado1 " + d1);
////                            System.out.println("dado2 " + d2);
//
//                             int d1 = 1 + D.nextInt(6);
//                             int d2 = 1 + D.nextInt(6);
//                             System.out.println("dado1  "+d1);
//                             System.out.println("dado1  "+d1);
//                             
//                            switch (d1){
//                                 case 1:
//                                lblD1.setIcon(new ImageIcon(getClass().getResource("images/1.png")));
//                                break;
//                                case 2:
//                                lblD1.setIcon(new ImageIcon(getClass().getResource("images/2.png")));
//                                break;
//                                case 3:
//                                lblD1.setIcon(new ImageIcon(getClass().getResource("images/3.png")));
//                                break;
//                                case 4:
//                                lblD1.setIcon(new ImageIcon(getClass().getResource("images/4.png")));
//                                break;
//                                case 5:
//                                lblD1.setIcon(new ImageIcon(getClass().getResource("images/5.png")));
//                                break;
//                                case 6:
//                                lblD1.setIcon(new ImageIcon(getClass().getResource("images/6.png")));
//                                break;
//                                default:
//
//                                break;
//                                }
//                                
//                                
//                            
//                            switch (d2){
//
//                                    case 1:
//                                    lblD2.setIcon(new ImageIcon(getClass().getResource("images/1.png")));
//                                    break;
//                                    case 2:
//                                    lblD2.setIcon(new ImageIcon(getClass().getResource("images/2.png")));
//                                    break;
//                                    case 3:
//                                    lblD2.setIcon(new ImageIcon(getClass().getResource("images/3.png")));
//                                    break;
//                                    case 4:
//                                    lblD2.setIcon(new ImageIcon(getClass().getResource("images/4.png")));
//                                    break;
//                                    case 5:
//                                    lblD2.setIcon(new ImageIcon(getClass().getResource("images/5.png")));
//                                    break;
//                                    case 6:
//                                    lblD2.setIcon(new ImageIcon(getClass().getResource("images/6.png")));
//                                    break;
//                                    default:
//
//                                    break;
//
//                                }
//                            
//                                
//                            
//                                   
//                                    
//                                
//                        }
//                            
//                            
//                        
//                    
//                }
//        }
    }//GEN-LAST:event_btnplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new number().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnConfigParams;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnTry;
    private javax.swing.JButton btnplay;
    private javax.swing.JComboBox<String> cbxLeven;
    private javax.swing.JComboBox<String> cbxNumP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblPares;
    private javax.swing.JPanel pnlConfigZone;
    private javax.swing.JPanel pnlPairs;
    private javax.swing.JPanel pnlZonePlay;
    // End of variables declaration//GEN-END:variables
}
